import {
  Archive,
  Atom,
  Baby,
  Banknote,
  Bike,
  Blocks,
  Book,
  BookOpen,
  Bot,
  Box,
  Brain,
  Briefcase,
  Brush,
  Bug,
  Building2,
  Calendar,
  Camera,
  Car,
  ChartColumn,
  ChartPie,
  Cloud,
  Code,
  Coffee,
  Compass,
  Cpu,
  CreditCard,
  Database,
  Dumbbell,
  Factory,
  FileText,
  Film,
  Flag,
  Flame,
  FlaskConical,
  Folder,
  Gamepad2,
  Gift,
  GitBranch,
  Globe,
  GraduationCap,
  Hammer,
  Handshake,
  HardDrive,
  Headphones,
  Heart,
  HeartPulse,
  House,
  Kanban,
  KeyRound,
  Landmark,
  Laptop,
  Leaf,
  Library,
  Lightbulb,
  ListChecks,
  Mail,
  Map,
  Megaphone,
  MessagesSquare,
  Microscope,
  Monitor,
  Moon,
  Mountain,
  Music,
  Network,
  Newspaper,
  Package,
  Palette,
  PawPrint,
  PenTool,
  PiggyBank,
  Pill,
  Plane,
  Presentation,
  Receipt,
  Rocket,
  Scale,
  School,
  Server,
  Shield,
  Ship,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Sprout,
  Star,
  Stethoscope,
  Store,
  Sun,
  Target,
  Telescope,
  Tent,
  Terminal,
  TrainFront,
  TreePine,
  Trophy,
  Truck,
  Users,
  Utensils,
  Wallet,
  Wifi,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/* Icone per workspace, progetti, sottoprogetti e sezioni, salvate come
   "lucide:<nome>". Ognuna ha parole chiave in italiano e inglese per la
   ricerca nel selettore. Tutte a tratto, dallo stesso set (docs/REDESIGN.md § 10). */

export interface IconEntry {
  name: string;
  icon: LucideIcon;
  keywords: string;
}

export const ICONS: IconEntry[] = [
  { name: 'briefcase', icon: Briefcase, keywords: 'lavoro ufficio work office' },
  { name: 'building2', icon: Building2, keywords: 'azienda edificio company building' },
  { name: 'landmark', icon: Landmark, keywords: 'banca istituzione bank institution' },
  { name: 'store', icon: Store, keywords: 'negozio shop store' },
  { name: 'factory', icon: Factory, keywords: 'fabbrica produzione factory' },
  { name: 'handshake', icon: Handshake, keywords: 'clienti accordo client deal' },
  { name: 'users', icon: Users, keywords: 'team persone people' },
  { name: 'presentation', icon: Presentation, keywords: 'presentazione riunione meeting slides' },
  { name: 'megaphone', icon: Megaphone, keywords: 'marketing comunicazione announce' },
  { name: 'kanban', icon: Kanban, keywords: 'progetto board attivita tasks' },
  { name: 'list-checks', icon: ListChecks, keywords: 'checklist cose da fare todo' },
  { name: 'calendar', icon: Calendar, keywords: 'calendario agenda schedule' },
  { name: 'mail', icon: Mail, keywords: 'posta email' },
  { name: 'messages-square', icon: MessagesSquare, keywords: 'chat messaggi messages' },
  { name: 'chart-column', icon: ChartColumn, keywords: 'grafico report dati chart' },
  { name: 'chart-pie', icon: ChartPie, keywords: 'statistiche analisi analytics' },
  { name: 'target', icon: Target, keywords: 'obiettivo goal' },
  { name: 'flag', icon: Flag, keywords: 'traguardo milestone' },
  { name: 'trophy', icon: Trophy, keywords: 'successo premio award' },
  { name: 'code', icon: Code, keywords: 'codice sviluppo code dev' },
  { name: 'terminal', icon: Terminal, keywords: 'terminale console shell' },
  { name: 'git-branch', icon: GitBranch, keywords: 'git repository branch' },
  { name: 'bug', icon: Bug, keywords: 'bug errore debug' },
  { name: 'workflow', icon: Workflow, keywords: 'processo flusso bpm workflow' },
  { name: 'blocks', icon: Blocks, keywords: 'moduli componenti modules' },
  { name: 'box', icon: Box, keywords: 'pacchetto prodotto package' },
  { name: 'package', icon: Package, keywords: 'rilascio release package' },
  { name: 'database', icon: Database, keywords: 'database dati sql' },
  { name: 'server', icon: Server, keywords: 'server backend infrastruttura' },
  { name: 'cloud', icon: Cloud, keywords: 'cloud hosting' },
  { name: 'network', icon: Network, keywords: 'rete network' },
  { name: 'cpu', icon: Cpu, keywords: 'hardware processore chip' },
  { name: 'hard-drive', icon: HardDrive, keywords: 'disco archivio storage' },
  { name: 'laptop', icon: Laptop, keywords: 'computer portatile laptop' },
  { name: 'monitor', icon: Monitor, keywords: 'schermo desktop' },
  { name: 'smartphone', icon: Smartphone, keywords: 'telefono mobile app' },
  { name: 'shield', icon: Shield, keywords: 'sicurezza security' },
  { name: 'key-round', icon: KeyRound, keywords: 'accessi chiavi credentials' },
  { name: 'bot', icon: Bot, keywords: 'automazione bot ai' },
  { name: 'brain', icon: Brain, keywords: 'intelligenza ai idee mind' },
  { name: 'sparkles', icon: Sparkles, keywords: 'novita magia new ai' },
  { name: 'rocket', icon: Rocket, keywords: 'lancio startup launch' },
  { name: 'lightbulb', icon: Lightbulb, keywords: 'idea innovazione' },
  { name: 'flask-conical', icon: FlaskConical, keywords: 'laboratorio esperimenti lab' },
  { name: 'microscope', icon: Microscope, keywords: 'ricerca science research' },
  { name: 'atom', icon: Atom, keywords: 'fisica scienza science' },
  { name: 'globe', icon: Globe, keywords: 'web sito internet' },
  { name: 'wifi', icon: Wifi, keywords: 'connessione wireless' },
  { name: 'file-text', icon: FileText, keywords: 'documenti documents' },
  { name: 'folder', icon: Folder, keywords: 'cartella folder' },
  { name: 'archive', icon: Archive, keywords: 'archivio archive' },
  { name: 'book-open', icon: BookOpen, keywords: 'documentazione lettura docs' },
  { name: 'book', icon: Book, keywords: 'libro manuale book' },
  { name: 'library', icon: Library, keywords: 'biblioteca risorse library' },
  { name: 'graduation-cap', icon: GraduationCap, keywords: 'studio universita corso study' },
  { name: 'school', icon: School, keywords: 'scuola school' },
  { name: 'newspaper', icon: Newspaper, keywords: 'notizie blog news' },
  { name: 'pen-tool', icon: PenTool, keywords: 'design grafica vector' },
  { name: 'palette', icon: Palette, keywords: 'design colori arte art' },
  { name: 'brush', icon: Brush, keywords: 'creativita pittura paint' },
  { name: 'camera', icon: Camera, keywords: 'foto fotografia photo' },
  { name: 'film', icon: Film, keywords: 'video cinema movie' },
  { name: 'music', icon: Music, keywords: 'musica audio' },
  { name: 'headphones', icon: Headphones, keywords: 'podcast ascolto audio' },
  { name: 'gamepad2', icon: Gamepad2, keywords: 'giochi gaming' },
  { name: 'house', icon: House, keywords: 'casa home' },
  { name: 'heart', icon: Heart, keywords: 'personale famiglia love' },
  { name: 'baby', icon: Baby, keywords: 'bambini figli kids' },
  { name: 'paw-print', icon: PawPrint, keywords: 'animali pets' },
  { name: 'heart-pulse', icon: HeartPulse, keywords: 'salute health' },
  { name: 'stethoscope', icon: Stethoscope, keywords: 'medico visite doctor' },
  { name: 'pill', icon: Pill, keywords: 'farmaci medicine' },
  { name: 'dumbbell', icon: Dumbbell, keywords: 'sport palestra fitness' },
  { name: 'bike', icon: Bike, keywords: 'bici ciclismo bike' },
  { name: 'wallet', icon: Wallet, keywords: 'finanze portafoglio money' },
  { name: 'piggy-bank', icon: PiggyBank, keywords: 'risparmi savings' },
  { name: 'credit-card', icon: CreditCard, keywords: 'carta pagamenti payments' },
  { name: 'banknote', icon: Banknote, keywords: 'soldi spese cash' },
  { name: 'receipt', icon: Receipt, keywords: 'fatture ricevute invoices' },
  { name: 'scale', icon: Scale, keywords: 'legale contratti legal' },
  { name: 'shopping-cart', icon: ShoppingCart, keywords: 'acquisti spesa shopping' },
  { name: 'gift', icon: Gift, keywords: 'regali gifts' },
  { name: 'utensils', icon: Utensils, keywords: 'cucina ricette cooking' },
  { name: 'coffee', icon: Coffee, keywords: 'caffe pausa break' },
  { name: 'car', icon: Car, keywords: 'auto macchina car' },
  { name: 'plane', icon: Plane, keywords: 'viaggi volo travel' },
  { name: 'train-front', icon: TrainFront, keywords: 'treno trasporti train' },
  { name: 'ship', icon: Ship, keywords: 'nave crociera boat' },
  { name: 'map', icon: Map, keywords: 'mappa luoghi map' },
  { name: 'compass', icon: Compass, keywords: 'esplorazione orientamento' },
  { name: 'mountain', icon: Mountain, keywords: 'montagna escursioni hiking' },
  { name: 'tent', icon: Tent, keywords: 'campeggio vacanze camping' },
  { name: 'sprout', icon: Sprout, keywords: 'giardino piante garden' },
  { name: 'tree-pine', icon: TreePine, keywords: 'natura nature' },
  { name: 'leaf', icon: Leaf, keywords: 'ecologia ambiente green' },
  { name: 'sun', icon: Sun, keywords: 'estate sole summer' },
  { name: 'moon', icon: Moon, keywords: 'notte night' },
  { name: 'zap', icon: Zap, keywords: 'energia veloce energy' },
  { name: 'flame', icon: Flame, keywords: 'priorita urgente hot' },
  { name: 'star', icon: Star, keywords: 'importante preferito star' },
  { name: 'hammer', icon: Hammer, keywords: 'lavori casa diy' },
  { name: 'wrench', icon: Wrench, keywords: 'manutenzione strumenti tools' },
  { name: 'truck', icon: Truck, keywords: 'spedizioni logistica shipping' },
  { name: 'telescope', icon: Telescope, keywords: 'astronomia visione' },
];

export const ICON_LIBRARY: Record<string, LucideIcon> = Object.fromEntries(
  ICONS.map((entry) => [entry.name, entry.icon]),
);
